### ISSUE TITLE
261 galaxies activated

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/network-explorer#2]
https://network.urbit.org/?nodes=galaxy&timeRange=year

![2022-04-14_07h34m32s](https://user-images.githubusercontent.com/77721746/163256639-6c941b4c-6c52-4dd4-a397-19398fbc54c4.png)

**Comment by tinnus-napbus** [comment]
@pkova

**Comment by pkova** [comment]
Had some duplicate events in the database, fixed now.
